### ISSUE TITLE
请问应该如何部署在vercel呢

### ISSUE THREAD

**Issue by songyp0505** [duolabmeng6/pro-api#2]
好像只看到了docker部署方式，请问vercel上可以用吗，自己用，好像也用不到那么多后台数据库

**Comment by duolabmeng6** [comment]
等我测试一下看看

**Comment by duolabmeng6** [comment]
## vercel 部署


点击下面的按钮一键部署到 Vercel：

[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Fduolabmeng6%2Fpro-api&env=config_url,secret_key&project-name=pro-api&repository-name=pro-api)

部署时需要设置以下环境变量：

- `config_url`: 远程配置文件的 URL
- `secret_key`: 用于加密的密钥（如果不需要加密，可以留空）如果需要加密，请使用 aes-128-ecb 加密 不加密就给明文的配置内容

部署完成后，访问 Vercel 分配的域名即可使用 API。

注意：请确保您的远程配置文件 (`config_url`) 可以被公开访问，否则 Vercel 将无法获取配置信息。
