### ISSUE TITLE
负载均衡那里的注释是不是有问题

### ISSUE THREAD

**Issue by suneliw** [duolabmeng6/pro-api#4]
![image](https://github.com/user-attachments/assets/7876e3e6-c6bf-439a-8ff9-e4b270acba2c)
不知道我理解的对不对，假设：
provider1:
    gpt-4o: 2

provider2:
    gpt-4o: 5

那么请求gpt-4o时有2/7的概率去到provider1，5/7的概率去到provider2。

**Comment by duolabmeng6** [comment]
就是这样啊，对的，没问题，对服务下的模型负载均衡值都是独立的
